/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Frames.glb --transform -k
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Frames(props) {
  const { nodes, materials } = useGLTF('/models/Frames-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Walls" position={[2, -2, -2]} scale={[1, 1.33, 1]}>
        <group name="Frames" position={[-2.78, 2.63, -0.72]} rotation={[Math.PI / 2, 0, 0.02]} scale={[1, 1, 0.75]}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['dark purple']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.006']} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['Material.004']} />
          <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials['Material.005']} />
          <mesh name="Plane_4" geometry={nodes.Plane_4.geometry} material={materials['Material.008']} />
          <mesh name="Plane_5" geometry={nodes.Plane_5.geometry} material={materials['Material.009']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Frames-transformed.glb')
