/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 NikeShoes.glb --transform -k
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
export default function NikeShoes(props) {
  const { nodes, materials } = useGLTF('/models/NikeShoes-transformed.glb')
  const shoe1 = useRef()
  const shoe2 = useRef()
  const shoe3 = useRef()
  const shoe4 = useRef()

  const shoeAnimation = () => {
    gsap.from([shoe1.current.scale,shoe2.current.scale,shoe3.current.scale,shoe4.current.scale], { x: 0, y: 0, z: 0,duration:.3,delay: .7, ease: 'power3.out', stagger: .1})
  }
  useEffect(() => {
    shoeAnimation()
  },[])

  return (
    <group {...props} dispose={null}>
      <group name="NikeLogo" position={[2.39, 2.24, 4.48]} ref={shoe1}>
        <mesh name="NikeLogo_1" geometry={nodes.NikeLogo_1.geometry} material={materials['nikeLogo.002']} />
        <mesh name="NikeLogo_2" geometry={nodes.NikeLogo_2.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_3" geometry={nodes.NikeLogo_3.geometry} material={materials['Material.016']} />
        <mesh name="NikeLogo_4" geometry={nodes.NikeLogo_4.geometry} material={materials['Material.017']} />
        <mesh name="NikeLogo_5" geometry={nodes.NikeLogo_5.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_6" geometry={nodes.NikeLogo_6.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_7" geometry={nodes.NikeLogo_7.geometry} material={materials['Material.017']} />
        <mesh name="NikeLogo_8" geometry={nodes.NikeLogo_8.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_9" geometry={nodes.NikeLogo_9.geometry} material={materials['tongueMaterial.002']} />
        <mesh name="NikeLogo_10" geometry={nodes.NikeLogo_10.geometry} material={materials['topTongueMaterial.002']} />
        <mesh name="NikeLogo_11" geometry={nodes.NikeLogo_11.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_12" geometry={nodes.NikeLogo_12.geometry} material={materials.Aqua} />
      </group>
      <group name="NikeLogo001" position={[2.39, 1.18, 4.48]} ref={shoe2}>
        <mesh name="NikeLogo_1" geometry={nodes.NikeLogo_1.geometry} material={materials['nikeLogo.002']} />
        <mesh name="NikeLogo_2" geometry={nodes.NikeLogo_2.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_3" geometry={nodes.NikeLogo_3.geometry} material={materials['Material.016']} />
        <mesh name="NikeLogo_4" geometry={nodes.NikeLogo_4.geometry} material={materials['Material.017']} />
        <mesh name="NikeLogo_5" geometry={nodes.NikeLogo_5.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_6" geometry={nodes.NikeLogo_6.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_7" geometry={nodes.NikeLogo_7.geometry} material={materials['Material.017']} />
        <mesh name="NikeLogo_8" geometry={nodes.NikeLogo_8.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_9" geometry={nodes.NikeLogo_9.geometry} material={materials['tongueMaterial.002']} />
        <mesh name="NikeLogo_10" geometry={nodes.NikeLogo_10.geometry} material={materials['topTongueMaterial.002']} />
        <mesh name="NikeLogo_11" geometry={nodes.NikeLogo_11.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_12" geometry={nodes.NikeLogo_12.geometry} material={materials.Aqua} />
      </group>
      <group name="NikeLogo002" position={[2.39, 0.27, 4.48]} ref={shoe3}>
        <mesh name="NikeLogo_1" geometry={nodes.NikeLogo_1.geometry} material={materials['nikeLogo.002']} />
        <mesh name="NikeLogo_2" geometry={nodes.NikeLogo_2.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_3" geometry={nodes.NikeLogo_3.geometry} material={materials['Material.016']} />
        <mesh name="NikeLogo_4" geometry={nodes.NikeLogo_4.geometry} material={materials['Material.017']} />
        <mesh name="NikeLogo_5" geometry={nodes.NikeLogo_5.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_6" geometry={nodes.NikeLogo_6.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_7" geometry={nodes.NikeLogo_7.geometry} material={materials['Material.017']} />
        <mesh name="NikeLogo_8" geometry={nodes.NikeLogo_8.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_9" geometry={nodes.NikeLogo_9.geometry} material={materials['tongueMaterial.002']} />
        <mesh name="NikeLogo_10" geometry={nodes.NikeLogo_10.geometry} material={materials['topTongueMaterial.002']} />
        <mesh name="NikeLogo_11" geometry={nodes.NikeLogo_11.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_12" geometry={nodes.NikeLogo_12.geometry} material={materials.Aqua} />
      </group>
      <group name="NikeLogo003" position={[2.39, -0.64, 4.48]} ref={shoe4}>
        <mesh name="NikeLogo_1" geometry={nodes.NikeLogo_1.geometry} material={materials['nikeLogo.002']} />
        <mesh name="NikeLogo_2" geometry={nodes.NikeLogo_2.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_3" geometry={nodes.NikeLogo_3.geometry} material={materials['Material.016']} />
        <mesh name="NikeLogo_4" geometry={nodes.NikeLogo_4.geometry} material={materials['Material.017']} />
        <mesh name="NikeLogo_5" geometry={nodes.NikeLogo_5.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_6" geometry={nodes.NikeLogo_6.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_7" geometry={nodes.NikeLogo_7.geometry} material={materials['Material.017']} />
        <mesh name="NikeLogo_8" geometry={nodes.NikeLogo_8.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_9" geometry={nodes.NikeLogo_9.geometry} material={materials['tongueMaterial.002']} />
        <mesh name="NikeLogo_10" geometry={nodes.NikeLogo_10.geometry} material={materials['topTongueMaterial.002']} />
        <mesh name="NikeLogo_11" geometry={nodes.NikeLogo_11.geometry} material={materials.Aqua} />
        <mesh name="NikeLogo_12" geometry={nodes.NikeLogo_12.geometry} material={materials.Aqua} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/NikeShoes-transformed.glb')
