/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 OfficeComputer.glb --transform -k
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
export default function OfficeComputer(props) {
  const { nodes, materials } = useGLTF('/models/OfficeComputer-transformed.glb')

  const computer = useRef()

  const computerAnimation = () => {
    gsap.from(computer.current.scale, { x: 0, y: 0, z: 0, duration:.5,delay: .6, ease: 'power1.out'})
  }
  useEffect(() => {
    computerAnimation()
  },[])

  return (
    <group {...props} dispose={null}>
      <group name="Walls" position={[2, -2, -2]} scale={[1, 1.33, 1]} >
        <group name="Monitor" position={[-4.99, 1.49, -0.14]} scale={[1.28, 0.96, 1.28]} ref={computer}>
          <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials['dark purple']} />
          <mesh name="Plane020_1" geometry={nodes.Plane020_1.geometry} material={materials['Black.002']} />
          <mesh name="Plane020_2" geometry={nodes.Plane020_2.geometry} material={materials['darkest purple']} />
          <mesh name="Plane020_3" geometry={nodes.Plane020_3.geometry} material={materials.Black} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/OfficeComputer-transformed.glb')
